#!/usr/bin/env python3
"""Build and deploy the Omnigent Databricks App.

Steps, in order:

1. Build the ``omnigent`` wheel from the repo root. The wheel bundles the
   prebuilt web-UI assets (``omnigent/server/static/web-ui``) that a
   source-only checkout can't regenerate, so make sure that bundle is present
   (CI builds it) before running this — otherwise the deployed app serves no
   UI.
2. Copy the wheel and a vendored copy of the generic Docker entrypoint
   (``deploy/docker/entrypoint.py`` → ``src/_omnigent_entrypoint.py``) into the
   app source folder, and point ``src/requirements.txt`` at the wheel. The
   deployed app source is just ``src/``; vendoring keeps ``app.py``'s reuse of
   the shared entrypoint working there.
3. ``databricks bundle deploy`` to upload the bundle and create/update the app.

Then start it with ``databricks bundle run omnigent_server -t <target>`` and
grant the app's service principal Lakebase access with ``grant_sp_perms.py``.

Usage::

    python deploy/databricks/deploy.py -t dev
    python deploy/databricks/deploy.py -t prod --skip-build   # reuse wheel
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parents[1]
_SRC_DIR = _HERE / "src"
_DOCKER_ENTRYPOINT = _REPO_ROOT / "deploy" / "docker" / "entrypoint.py"
_VENDORED_ENTRYPOINT = _SRC_DIR / "_omnigent_entrypoint.py"
_REQUIREMENTS = _SRC_DIR / "requirements.txt"


def _run(cmd: list[str], cwd: Path | None = None) -> None:
    """Run *cmd*, echoing it; raise ``CalledProcessError`` on failure."""
    print(f"$ {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def build_wheel() -> Path:
    """Build the omnigent wheel into ``dist/`` and return its path."""
    dist = _REPO_ROOT / "dist"
    for stale in dist.glob("omnigent-*.whl"):
        stale.unlink()
    _run(["uv", "build", "--wheel", "--out-dir", str(dist)], cwd=_REPO_ROOT)
    wheels = sorted(dist.glob("omnigent-*.whl"))
    if not wheels:
        raise SystemExit("wheel build produced no omnigent-*.whl in dist/")
    return wheels[-1]


def stage_source(wheel: Path) -> None:
    """Copy the wheel + vendored entrypoint into ``src/`` and pin requirements."""
    # Drop any previously staged wheels so requirements.txt has one target.
    for stale in _SRC_DIR.glob("omnigent-*.whl"):
        stale.unlink()
    shutil.copy2(wheel, _SRC_DIR / wheel.name)
    shutil.copy2(_DOCKER_ENTRYPOINT, _VENDORED_ENTRYPOINT)
    _REQUIREMENTS.write_text(
        "# Generated by deploy.py — points at the wheel staged alongside this file.\n"
        f"./{wheel.name}[databricks]\n"
    )
    print(f"staged {wheel.name}, vendored entrypoint, pinned requirements.txt", flush=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-t", "--target", default="dev", help="DAB target (dev/prod)")
    parser.add_argument(
        "--skip-build", action="store_true", help="reuse the wheel already in dist/"
    )
    args = parser.parse_args(argv)

    if args.skip_build:
        wheels = sorted((_REPO_ROOT / "dist").glob("omnigent-*.whl"))
        if not wheels:
            raise SystemExit("--skip-build set but no omnigent-*.whl in dist/")
        wheel = wheels[-1]
    else:
        wheel = build_wheel()

    stage_source(wheel)
    _run(["databricks", "bundle", "deploy", "-t", args.target], cwd=_HERE)
    print(
        "\nDeployed. Start the app and grant Lakebase access:\n"
        f"  databricks bundle run omnigent_server -t {args.target}\n"
        f"  python {Path(__file__).parent / 'grant_sp_perms.py'} "
        "--app-name omnigent-server --instance <lakebase-instance> --superuser",
        flush=True,
    )


if __name__ == "__main__":
    main()
