/**
 * User-activity tracking for browser-session idle timeout.
 *
 * Every API request carries {@link ACTIVITY_AGE_HEADER}: whole seconds since
 * the user last interacted with the app in this browser. The server renews the
 * session cookie only up to that interaction plus the idle window, so
 * background polling (sidebar refresh, status timers, stream reconnects) keeps
 * a tab connected but never keeps an unattended browser signed in. Only real
 * input counts — pointer, click, key, wheel and touch, generated by the
 * browser rather than by script — plus the user returning to the page (it was
 * hidden or blurred, and is shown or focused again); scrolling and focus moves
 * the app makes itself don't. Loading, reloading or restoring a page is not an
 * interaction: until the first real one (in this tab or another) requests
 * carry no age, so they never renew.
 *
 * Tabs share one session cookie, so they also share the last-interaction time
 * through `localStorage` ({@link SHARED_ACTIVITY_KEY}): a request from an idle
 * tab reports the most recent interaction in any tab. Without usable storage
 * each tab falls back to its own interactions. A time more than
 * {@link FUTURE_SKEW_MS} ahead of the clock (it was set back) is invalid, and
 * stays invalid once seen — even after the clock catches up to it — so it
 * sends no age until a real interaction replaces it.
 *
 * The age is client-reported: it protects an unattended screen, not against
 * code already running with the user's cookie.
 */

/** Request header carrying the seconds since the last user interaction. */
export const ACTIVITY_AGE_HEADER = "X-Omnigent-Activity-Age";

/** Interactions closer together than this record only once. */
export const ACTIVITY_THROTTLE_MS = 1_000;

/** `localStorage` key holding the latest interaction (epoch ms) across tabs. */
export const SHARED_ACTIVITY_KEY = "omnigent.session.lastInteractionMs";

/** A recorded time at most this far ahead of the clock is still trusted. */
export const FUTURE_SKEW_MS = 5_000;

// No `scroll`: it also fires for programmatic scrolling (e.g. following a
// streaming reply), which is not the user. `click` covers activation by
// assistive technology, which sends no pointerdown or keydown.
const INTERACTION_EVENTS = ["pointerdown", "click", "keydown", "wheel", "touchstart"] as const;

// This tab's last interaction; ``null`` until the user does something.
let lastActivityMs: number | null = null;
// A shared value already found too far in the future; refused from then on,
// so it can't become valid again when the clock catches up.
let rejectedStoredMs: number | null = null;
// Whether this page saw itself hidden or blurred since it last counted a
// return; only then does being shown or focused mean the user came back.
let awayObserved = false;
let listening = false;

/** Whether *event* came from the user rather than from script. */
let isUserEvent = (event: Event): boolean => event.isTrusted;

function isFuture(time: number, nowMs: number): boolean {
  return time > nowMs + FUTURE_SKEW_MS;
}

/** This tab's last interaction, dropped for good once it is seen in the future. */
function localActivity(nowMs: number): number | null {
  if (lastActivityMs !== null && isFuture(lastActivityMs, nowMs)) lastActivityMs = null;
  return lastActivityMs;
}

/** Stop trusting *value* and remove it from storage so other tabs agree. */
function rejectStoredActivity(value: number): void {
  rejectedStoredMs = value;
  try {
    if (Number(window.localStorage.getItem(SHARED_ACTIVITY_KEY)) === value) {
      window.localStorage.removeItem(SHARED_ACTIVITY_KEY);
    }
  } catch {
    // Storage unavailable: this tab still refuses the value from memory.
  }
}

/** The shared timestamp, or ``null`` when storage is unusable or it is invalid. */
function readStoredActivity(nowMs: number): number | null {
  let value: number;
  try {
    const raw = window.localStorage.getItem(SHARED_ACTIVITY_KEY);
    if (raw === null) return null;
    value = Number(raw);
  } catch {
    return null;
  }
  if (!Number.isFinite(value) || value === rejectedStoredMs) return null;
  if (isFuture(value, nowMs)) {
    rejectStoredActivity(value);
    return null;
  }
  return value;
}

/**
 * Publish *nowMs* to other tabs. Re-reads just before writing and keeps a
 * newer valid value another tab wrote; an invalid (far-future) value is
 * replaced.
 */
function writeSharedActivity(nowMs: number): void {
  const stored = readStoredActivity(nowMs);
  if (stored !== null && stored >= nowMs) return;
  try {
    window.localStorage.setItem(SHARED_ACTIVITY_KEY, String(nowMs));
  } catch {
    // Unavailable, full or blocked storage: keep per-tab tracking only.
  }
}

/**
 * Record a user interaction at *nowMs*, at most once per
 * {@link ACTIVITY_THROTTLE_MS}, and share it with other tabs.
 */
export function recordActivity(nowMs: number = Date.now()): void {
  const local = localActivity(nowMs);
  if (local !== null && nowMs - local < ACTIVITY_THROTTLE_MS) return;
  lastActivityMs = nowMs;
  writeSharedActivity(nowMs);
}

function onInteraction(event: Event): void {
  if (isUserEvent(event)) recordActivity();
}

// Coming back to a page this instance saw hidden or blurred means the user
// switched to it, so it counts as intent; the state at load or restore doesn't.
function onReturn(): void {
  if (!awayObserved) return;
  awayObserved = false;
  recordActivity();
}

function onVisibilityChange(event: Event): void {
  if (!isUserEvent(event)) return;
  if (document.visibilityState === "hidden") awayObserved = true;
  else if (document.visibilityState === "visible") onReturn();
}

// Only the window itself losing or gaining focus, not focus moving between
// elements inside the page.
function onWindowBlur(event: FocusEvent): void {
  if (event.target === event.currentTarget && isUserEvent(event)) awayObserved = true;
}

function onWindowFocus(event: FocusEvent): void {
  if (event.target === event.currentTarget && isUserEvent(event)) onReturn();
}

// Leaving or being restored from the back/forward cache is not a return.
function onPageTransition(): void {
  awayObserved = false;
}

/**
 * Start listening for interactions (idempotent). Called lazily by
 * {@link activityAgeSeconds}, so any entry point that makes API requests is
 * covered without its own setup.
 */
export function startActivityTracking(): void {
  if (listening || typeof window === "undefined") return;
  listening = true;
  const options = { capture: true, passive: true };
  for (const event of INTERACTION_EVENTS) {
    window.addEventListener(event, onInteraction, options);
  }
  window.addEventListener("focus", onWindowFocus, { passive: true });
  window.addEventListener("blur", onWindowBlur, { passive: true });
  window.addEventListener("pagehide", onPageTransition, { passive: true });
  window.addEventListener("pageshow", onPageTransition, { passive: true });
  document.addEventListener("visibilitychange", onVisibilityChange, options);
}

/**
 * Whole seconds since the latest valid interaction in this tab or any other
 * (never negative), or ``null`` when there is none. Never publishes activity;
 * it only removes a shared value found to be invalid.
 */
export function activityAgeSeconds(nowMs: number = Date.now()): number | null {
  startActivityTracking();
  const candidates = [localActivity(nowMs), readStoredActivity(nowMs)];
  const valid = candidates.filter((time): time is number => time !== null);
  if (valid.length === 0) return null;
  return Math.max(0, Math.floor((nowMs - Math.max(...valid)) / 1000));
}

/**
 * Return *init* with {@link ACTIVITY_AGE_HEADER} set, unless the caller
 * already set it or there is no valid interaction to report (then the
 * request cannot renew the session). Used by every same-origin API request.
 */
export function withActivityAge(init?: RequestInit): RequestInit {
  const headers = new Headers(init?.headers);
  if (!headers.has(ACTIVITY_AGE_HEADER)) {
    const age = activityAgeSeconds();
    if (age !== null) headers.set(ACTIVITY_AGE_HEADER, String(age));
  }
  return { ...init, headers };
}

/**
 * Test-only: decide which events count as user-generated. jsdom marks every
 * dispatched event untrusted; ``null`` restores the real ``isTrusted`` check.
 */
export function setUserEventCheckForTests(check: ((event: Event) => boolean) | null): void {
  isUserEvent = check ?? ((event: Event): boolean => event.isTrusted);
}

/**
 * Test-only: forget listeners, the shared value, any rejected value and the
 * event check, and set this tab's last interaction to *nowMs* (``null``: none
 * yet, as after a page load).
 */
export function resetActivityForTests(nowMs: number | null = null): void {
  if (listening && typeof window !== "undefined") {
    for (const event of INTERACTION_EVENTS) {
      window.removeEventListener(event, onInteraction, { capture: true });
    }
    window.removeEventListener("focus", onWindowFocus);
    window.removeEventListener("blur", onWindowBlur);
    window.removeEventListener("pagehide", onPageTransition);
    window.removeEventListener("pageshow", onPageTransition);
    document.removeEventListener("visibilitychange", onVisibilityChange, { capture: true });
  }
  listening = false;
  lastActivityMs = nowMs;
  rejectedStoredMs = null;
  awayObserved = false;
  setUserEventCheckForTests(null);
  try {
    window.localStorage.removeItem(SHARED_ACTIVITY_KEY);
  } catch {
    // Storage unavailable in this environment; nothing shared to forget.
  }
}
