import { dpiaCaseSnapshotSchema } from "./schemas";
import type {
  DpiaCaseSnapshot,
  EvidenceItem,
  PolicyPack,
  ReadinessDefinition,
  RiskItem,
} from "./types";

export const readinessDefinitions: ReadinessDefinition[] = [
  {
    id: "purpose-scope",
    label: "Purpose and scope defined",
    requiredFactIds: ["purpose", "intended-outcome", "data-subjects"],
  },
  {
    id: "lifecycle-flows",
    label: "Lifecycle and data flows mapped",
    requiredFactIds: ["data-sources", "processing-lifecycle", "system-landscape"],
  },
  {
    id: "legal-basis",
    label: "Legal basis and Article 9 condition assessable",
    requiredFactIds: ["legal-basis", "article-9-condition", "special-category-use"],
  },
  {
    id: "necessity-proportionality",
    label: "Necessity and proportionality assessable",
    requiredFactIds: ["necessity", "less-intrusive-means"],
  },
  {
    id: "student-harms-rights",
    label: "Student harms and rights assessable",
    requiredFactIds: ["score-influence", "human-review", "bias-testing"],
  },
  {
    id: "vendor-transfer",
    label: "Vendor, processor, and transfer facts evidenced",
    requiredFactIds: ["vendor", "hosting", "subprocessors", "international-access"],
  },
  {
    id: "security-controls",
    label: "Security controls evidenced",
    requiredFactIds: ["security-controls", "access-controls"],
  },
  {
    id: "transparency-retention",
    label: "Transparency, consultation, retention, and deletion evidenced",
    requiredFactIds: ["student-notice", "retention", "deletion-confirmation"],
  },
];

export const ukPolicyPack: PolicyPack = {
  jurisdiction: "UK",
  version: "uk-dpia-2026.08-demo.1",
  effectiveDate: "2026-08-01",
  rules: [
    {
      id: "uk-gdpr-art35",
      title: "DPIA trigger and high-risk assessment",
      source: "UK GDPR Article 35",
      guidance:
        "Assess whether the proposed processing is likely to result in a high risk, including systematic and extensive evaluation with significant effects and large-scale special-category processing.",
    },
    {
      id: "ico-high-risk-criteria",
      title: "ICO high-risk screening criteria",
      source: "ICO, Data protection impact assessments guidance",
      guidance:
        "Consider evaluation or scoring, automated decision-making, systematic monitoring, special-category data, matching datasets, vulnerable data subjects, innovative technology, and barriers to rights or services. Criteria inform judgement and do not mechanically decide the legal outcome.",
    },
    {
      id: "uk-gdpr-art5",
      title: "Fairness, transparency, minimisation, and storage limitation",
      source: "UK GDPR Article 5",
      guidance:
        "Document why each data source is necessary, how students are informed, how accuracy is managed, and why retention is limited to what is necessary.",
    },
    {
      id: "uk-gdpr-art6",
      title: "Lawful basis",
      source: "UK GDPR Article 6",
      guidance:
        "Identify and evidence a lawful basis for each processing purpose before deployment; public task requires a basis in law and a necessity assessment.",
    },
    {
      id: "uk-gdpr-art9",
      title: "Special-category condition",
      source: "UK GDPR Article 9 and Data Protection Act 2018 Schedule 1",
      guidance:
        "Identify an Article 9 condition and any associated DPA 2018 condition, safeguards, and policy-document requirement for disability or wellbeing data.",
    },
    {
      id: "uk-gdpr-art22",
      title: "Profiling and meaningful human involvement",
      source: "UK GDPR Article 22 and ICO guidance on AI and data protection",
      guidance:
        "Establish whether scores produce or materially influence decisions, whether human review is meaningful, and how students can contest outcomes.",
    },
    {
      id: "uk-gdpr-arts13-14",
      title: "Student transparency",
      source: "UK GDPR Articles 13 and 14",
      guidance:
        "Provide clear information about data sources, purposes, recipients, retention, profiling logic, expected consequences, and applicable rights.",
    },
    {
      id: "uk-gdpr-art28",
      title: "Processor governance",
      source: "UK GDPR Article 28",
      guidance:
        "Evidence processor instructions, confidentiality, security, subprocessor controls, assistance, deletion or return, and audit rights.",
    },
    {
      id: "uk-gdpr-chapter-v",
      title: "International transfers",
      source: "UK GDPR Chapter V",
      guidance:
        "Identify remote access and onward transfers, then document the transfer mechanism, risk assessment, and supplementary measures where required.",
    },
    {
      id: "uk-gdpr-art36",
      title: "Prior consultation",
      source: "UK GDPR Article 36",
      guidance:
        "Escalate for prior consultation where identified high residual risk cannot be reduced before processing begins.",
    },
  ],
};

const evidence: EvidenceItem[] = [
  {
    id: "ev-intake",
    title: "Project intake form",
    type: "Intake",
    filename: "01-project-intake.md",
    source: "Student Services",
    owner: "Programme Director",
    collectedAt: "2026-07-28T09:15:00Z",
    excerpt:
      "The service is support only. It predicts disengagement and recommends outreach; the score does not itself make a decision about a student.",
    supportedDimensionIds: ["purpose-scope", "necessity-proportionality", "student-harms-rights"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-data-dictionary",
    title: "Student-system and VLE data dictionary",
    type: "Data inventory",
    filename: "02-data-dictionary.md",
    source: "Registry and Digital Learning",
    owner: "Data Architecture Lead",
    collectedAt: "2026-07-29T13:20:00Z",
    excerpt:
      "Daily features include attendance, VLE logins, submission outcomes, library use, accommodation status, hardship-support indicator, and disability/wellbeing support flags.",
    supportedDimensionIds: ["lifecycle-flows", "legal-basis", "student-harms-rights"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-operating-procedure",
    title: "Student Success Alert operating procedure",
    type: "Procedure",
    filename: "03-operating-procedure.md",
    source: "Student Services",
    owner: "Head of Student Support",
    collectedAt: "2026-07-30T10:00:00Z",
    excerpt:
      "Persistent high-risk scores may be considered in attendance escalation and may prompt a fitness-to-study referral after review by an authorised member of staff.",
    supportedDimensionIds: ["purpose-scope", "student-harms-rights", "transparency-retention"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-privacy-notice",
    title: "Student privacy notice",
    type: "Transparency",
    filename: "04-student-privacy-notice.md",
    source: "Information Governance",
    owner: "University DPO",
    collectedAt: "2026-07-30T15:30:00Z",
    excerpt:
      "The notice describes learning analytics in aggregate but does not describe individual disengagement scores, combined support indicators, escalation consequences, or how a student can contest a score.",
    supportedDimensionIds: ["legal-basis", "student-harms-rights", "transparency-retention"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-retention-schedule",
    title: "University records-retention schedule",
    type: "Policy",
    filename: "05-retention-schedule.md",
    source: "Records Management",
    owner: "Records Manager",
    collectedAt: "2026-07-31T08:45:00Z",
    excerpt:
      "Student success analytics outputs: retain for the current academic year plus 90 days, then delete or irreversibly aggregate.",
    supportedDimensionIds: ["transparency-retention"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-vendor-dpa",
    title: "Vendor DPA and processing schedule",
    type: "Contract",
    filename: "06-vendor-dpa.md",
    source: "Procurement",
    owner: "Supplier Manager",
    collectedAt: "2026-07-31T11:10:00Z",
    excerpt:
      "Customer data and derived risk scores may be retained for 24 months after creation. Hosting region and support-access locations are specified in the service order, which was not included in the evidence pack.",
    supportedDimensionIds: ["vendor-transfer", "transparency-retention"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-model-card",
    title: "Model card and bias-test summary",
    type: "Model assurance",
    filename: "07-model-card.md",
    source: "Vendor",
    owner: "Vendor ML Lead",
    collectedAt: "2026-08-01T14:05:00Z",
    excerpt:
      "Validation reports aggregate precision and recall. Results by disability, ethnicity, age, gender, course, and intersectional group are not supplied; the tested university population is not identified.",
    supportedDimensionIds: ["necessity-proportionality", "student-harms-rights"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-security-questionnaire",
    title: "Security questionnaire",
    type: "Security assurance",
    filename: "08-security-questionnaire.md",
    source: "Vendor",
    owner: "Vendor Security Officer",
    collectedAt: "2026-08-01T16:40:00Z",
    excerpt:
      "Encryption is applied in transit and at rest. Customer roles are configurable, privileged actions are logged, annual penetration testing is commissioned, and incident notification is contractually required.",
    supportedDimensionIds: ["security-controls", "vendor-transfer"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-subprocessor-list",
    title: "Subprocessor list",
    type: "Processor record",
    filename: "09-subprocessor-list.md",
    source: "Vendor trust centre",
    owner: "Vendor Privacy Team",
    collectedAt: "2026-08-02T09:00:00Z",
    excerpt:
      "The list names cloud hosting, support, and telemetry suppliers but does not identify which receive Student Success Alert data, their processing locations, or whether US support staff can access customer content.",
    supportedDimensionIds: ["vendor-transfer"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-response-student-services",
    title: "Stakeholder response: Student Services",
    type: "Attributed response",
    filename: "10-response-student-services.md",
    source: "Student Services",
    owner: "Maya Bennett, Head of Student Support",
    collectedAt: "2026-08-06T10:15:00Z",
    excerpt:
      "Tutors see a risk band and contributing themes, not raw disability notes. A high band starts a conversation, but repeated alerts may be included in an attendance or fitness-to-study case file.",
    supportedDimensionIds: ["purpose-scope", "student-harms-rights", "security-controls"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-response-registry",
    title: "Stakeholder response: Registry",
    type: "Attributed response",
    filename: "11-response-registry.md",
    source: "Registry",
    owner: "Daniel Okafor, Deputy Academic Registrar",
    collectedAt: "2026-08-06T13:00:00Z",
    excerpt:
      "Registry proposes public task as the Article 6 basis. The legal gateway and the Article 9/DPA 2018 condition for disability and wellbeing indicators still require DPO confirmation.",
    supportedDimensionIds: ["legal-basis", "necessity-proportionality"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-response-security",
    title: "Stakeholder response: IT Security",
    type: "Attributed response",
    filename: "12-response-it-security.md",
    source: "IT Security",
    owner: "Priya Shah, Security Architect",
    collectedAt: "2026-08-07T09:40:00Z",
    excerpt:
      "SSO, MFA, role-based access, quarterly entitlement review, export logging, and a security-incident playbook are required before launch. Named role membership is not yet approved.",
    supportedDimensionIds: ["security-controls"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-response-disability",
    title: "Stakeholder response: Disability Services",
    type: "Attributed response",
    filename: "13-response-disability-services.md",
    source: "Disability Services",
    owner: "Amelia Lewis, Disability Services Manager",
    collectedAt: "2026-08-07T12:25:00Z",
    excerpt:
      "A support-registration flag might reduce missed support, but using it as a risk feature could expose status through inference and amplify historic access barriers. Student representatives have not been consulted.",
    supportedDimensionIds: ["necessity-proportionality", "student-harms-rights"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-response-schools",
    title: "Stakeholder response: Academic schools",
    type: "Attributed response",
    filename: "14-response-academic-schools.md",
    source: "Academic schools",
    owner: "Dr Samir Patel, Faculty Education Lead",
    collectedAt: "2026-08-08T08:50:00Z",
    excerpt:
      "Personal tutors need context and an explanation before acting. They should record independent judgement and must not treat a risk band as evidence of misconduct or lack of engagement.",
    supportedDimensionIds: ["student-harms-rights", "security-controls"],
    status: "current",
    synthetic: true,
  },
  {
    id: "ev-response-procurement",
    title: "Stakeholder response: Procurement",
    type: "Attributed response",
    filename: "15-response-procurement.md",
    source: "Procurement and vendor management",
    owner: "Chloe Martin, Supplier Manager",
    collectedAt: "2026-08-08T14:20:00Z",
    excerpt:
      "The vendor will negotiate a 15-month deletion period but has not accepted the university schedule. The missing service order and complete subprocessor-location matrix have been requested.",
    supportedDimensionIds: ["vendor-transfer", "transparency-retention"],
    status: "current",
    synthetic: true,
  },
];

const risks: RiskItem[] = [
  {
    id: "risk-false-positive",
    harm: "False-positive intervention or escalation",
    affectedSubjects: "Students incorrectly classified as disengaging",
    likelihood: "medium",
    severity: "high",
    inherentRating: "high",
    controls: ["Tutor review", "Contributing themes shown", "No automatic action"],
    mitigation:
      "Require recorded independent judgement, contest routes, and outcome sampling before escalation.",
    residualRating: "medium",
    owner: "Head of Student Support",
    dueDate: "2026-10-15",
  },
  {
    id: "risk-false-negative",
    harm: "Failure to identify a student who needs support",
    affectedSubjects: "Students whose circumstances are not represented by behavioural data",
    likelihood: "medium",
    severity: "high",
    inherentRating: "high",
    controls: [
      "Existing referral routes remain open",
      "Staff can initiate support without a score",
    ],
    mitigation: "Monitor false negatives and prohibit replacement of existing pastoral routes.",
    residualRating: "medium",
    owner: "Student Services Analytics Lead",
    dueDate: "2026-11-01",
  },
  {
    id: "risk-discrimination",
    harm: "Discriminatory impact on demographic or disability groups",
    affectedSubjects: "Disabled, international, minoritised, mature, and part-time students",
    likelihood: "high",
    severity: "high",
    inherentRating: "critical",
    controls: ["Aggregate model-card metrics", "Human review"],
    mitigation:
      "Complete representative subgroup and intersectional testing with release thresholds and independent review.",
    residualRating: "high",
    owner: "Model Governance Board",
    dueDate: "2026-09-30",
  },
  {
    id: "risk-disability-disclosure",
    harm: "Unnecessary disclosure of disability or wellbeing information",
    affectedSubjects: "Students registered with disability or wellbeing services",
    likelihood: "medium",
    severity: "high",
    inherentRating: "high",
    controls: ["Tutors receive themes rather than raw notes", "Role-based access"],
    mitigation:
      "Remove direct support flags unless necessity is demonstrated; test and prevent attribute inference.",
    residualRating: "medium",
    owner: "Disability Services Manager",
    dueDate: "2026-09-20",
  },
  {
    id: "risk-chilling-effect",
    harm: "Surveillance and chilling effects on learning behaviour",
    affectedSubjects: "All enrolled students",
    likelihood: "medium",
    severity: "medium",
    inherentRating: "medium",
    controls: ["Existing student privacy notice"],
    mitigation:
      "Consult students and publish layered notice explaining data signals, limits, consequences, and rights.",
    residualRating: "medium",
    owner: "Director of Student Experience",
    dueDate: "2026-10-01",
  },
  {
    id: "risk-function-creep",
    harm: "Function creep into attendance, conduct, or fitness-to-study decisions",
    affectedSubjects: "Students with persistent high-risk bands",
    likelihood: "high",
    severity: "high",
    inherentRating: "critical",
    controls: ["Procedure requires authorised staff review"],
    mitigation:
      "Separate support and escalation workflows, prohibit evidential use of scores, and require governance approval for purpose changes.",
    residualRating: "high",
    owner: "Academic Registrar",
    dueDate: "2026-09-15",
  },
  {
    id: "risk-unauthorised-access",
    harm: "Unauthorized access to individual risk scores",
    affectedSubjects: "All scored students",
    likelihood: "medium",
    severity: "high",
    inherentRating: "high",
    controls: ["SSO", "MFA", "Role-based access", "Export logging"],
    mitigation:
      "Approve named roles, implement quarterly entitlement review, and alert on bulk access or export.",
    residualRating: "medium",
    owner: "Security Architect",
    dueDate: "2026-09-30",
  },
  {
    id: "risk-transfer",
    harm: "International-transfer or subprocessor exposure",
    affectedSubjects: "All students represented in the vendor platform",
    likelihood: "medium",
    severity: "high",
    inherentRating: "high",
    controls: ["Vendor DPA", "Encryption", "Subprocessor notification clause"],
    mitigation:
      "Obtain hosting and access locations, map subprocessors, and complete transfer mechanism and risk assessment before upload.",
    residualRating: "high",
    owner: "Supplier Manager",
    dueDate: "2026-09-10",
  },
];

const seed: DpiaCaseSnapshot = {
  id: "student-success-alert",
  title: "Student Success Alert — AI Early-Warning and Intervention",
  owner: "Student Services Transformation",
  jurisdiction: "UK",
  stage: "Screening review",
  recommendation: "full-dpia-likely",
  snapshotLabel: "Validated demo snapshot",
  updatedAt: "2026-08-12T16:30:00Z",
  processingModel: {
    caseId: "student-success-alert",
    version: 3,
    updatedAt: "2026-08-12T16:30:00Z",
    facts: [
      {
        id: "purpose",
        section: "Purpose and intended outcomes",
        label: "Purpose",
        value:
          "Identify possible student disengagement early and recommend proportionate support outreach.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-intake", "ev-response-student-services"],
        dependentDimensionIds: ["purpose-scope", "necessity-proportionality"],
      },
      {
        id: "intended-outcome",
        section: "Purpose and intended outcomes",
        label: "Effect on students",
        value: "Support only; no significant effect is intended.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-intake", "ev-operating-procedure"],
        dependentDimensionIds: ["purpose-scope", "student-harms-rights"],
      },
      {
        id: "data-subjects",
        section: "Data subjects",
        label: "Data subjects",
        value:
          "Enrolled undergraduate and postgraduate students, including students receiving disability, wellbeing, accommodation, or financial support.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-data-dictionary"],
        dependentDimensionIds: ["purpose-scope", "student-harms-rights"],
      },
      {
        id: "data-sources",
        section: "Data categories",
        label: "Data sources",
        value:
          "Attendance, VLE, attainment, library, accommodation, financial support, disability, and wellbeing indicators.",
        lifecycleStage: "collection",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-data-dictionary"],
        dependentDimensionIds: ["lifecycle-flows", "legal-basis", "student-harms-rights"],
      },
      {
        id: "processing-lifecycle",
        section: "Business process",
        label: "Processing lifecycle",
        value:
          "Nightly extraction, vendor scoring, staff review, support outreach, monitored retention, and deletion or aggregation.",
        lifecycleStage: "use",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-data-dictionary", "ev-operating-procedure"],
        dependentDimensionIds: ["lifecycle-flows"],
      },
      {
        id: "system-landscape",
        section: "Systems and vendors",
        label: "Systems",
        value:
          "University student record, VLE, library, support systems, integration layer, and external Student Success SaaS.",
        lifecycleStage: "sharing",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-data-dictionary", "ev-vendor-dpa"],
        dependentDimensionIds: ["lifecycle-flows", "vendor-transfer"],
      },
      {
        id: "legal-basis",
        section: "Transparency and rights",
        label: "Proposed Article 6 basis",
        value:
          "Public task is proposed, subject to DPO confirmation of the legal gateway and necessity.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-response-registry"],
        dependentDimensionIds: ["legal-basis", "necessity-proportionality"],
      },
      {
        id: "article-9-condition",
        section: "Special-category data",
        label: "Proposed Article 9 condition",
        value:
          "Substantial public interest is proposed; the specific DPA 2018 Schedule 1 condition and safeguards require officer judgement.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-response-registry", "ev-response-disability"],
        dependentDimensionIds: ["legal-basis"],
      },
      {
        id: "special-category-use",
        section: "Special-category data",
        label: "Disability and wellbeing use",
        value:
          "Binary support-registration indicators are proposed as model features; raw case notes are excluded.",
        lifecycleStage: "use",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-data-dictionary", "ev-response-disability"],
        dependentDimensionIds: ["legal-basis", "student-harms-rights"],
      },
      {
        id: "necessity",
        section: "Purpose and intended outcomes",
        label: "Necessity case",
        value:
          "Existing support routes are reactive and fragmented; the proposal seeks earlier, prioritised outreach but has not demonstrated that every feature is necessary.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-intake", "ev-response-disability"],
        dependentDimensionIds: ["necessity-proportionality"],
      },
      {
        id: "less-intrusive-means",
        section: "Purpose and intended outcomes",
        label: "Less intrusive alternatives",
        value:
          "A reduced feature set, student-initiated check-ins, and cohort-level analytics are identified for comparison before launch.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-model-card", "ev-response-disability"],
        dependentDimensionIds: ["necessity-proportionality"],
      },
      {
        id: "score-influence",
        section: "AI/profiling and significant effects",
        label: "How scores influence action",
        value:
          "Intake says support only; the procedure and stakeholders permit repeated scores to enter escalation or fitness-to-study workflows.",
        lifecycleStage: "use",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-intake", "ev-operating-procedure", "ev-response-student-services"],
        dependentDimensionIds: ["student-harms-rights"],
      },
      {
        id: "human-review",
        section: "AI/profiling and significant effects",
        label: "Human review",
        value:
          "Authorised staff review the risk band and should record independent judgement before outreach or escalation.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-operating-procedure", "ev-response-schools"],
        dependentDimensionIds: ["student-harms-rights"],
      },
      {
        id: "bias-testing",
        section: "AI/profiling and significant effects",
        label: "Bias and accuracy testing",
        value:
          "Aggregate precision and recall are supplied; representative subgroup and intersectional results are missing.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-model-card"],
        dependentDimensionIds: ["student-harms-rights"],
      },
      {
        id: "vendor",
        section: "Systems and vendors",
        label: "Processor",
        value:
          "Synthetic supplier: Northstar Student Analytics Ltd, acting as processor under the university's instructions.",
        lifecycleStage: "sharing",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-vendor-dpa"],
        dependentDimensionIds: ["vendor-transfer"],
      },
      {
        id: "hosting",
        section: "Countries and transfers",
        label: "Model and database hosting",
        value: "",
        lifecycleStage: "storage",
        material: true,
        status: "missing",
        evidenceIds: [],
        dependentDimensionIds: ["vendor-transfer"],
      },
      {
        id: "subprocessors",
        section: "Systems and vendors",
        label: "Subprocessor data flows",
        value:
          "Supplier names are listed, but services, datasets, and processing locations are not mapped.",
        lifecycleStage: "sharing",
        material: true,
        status: "missing",
        evidenceIds: ["ev-subprocessor-list"],
        dependentDimensionIds: ["vendor-transfer"],
      },
      {
        id: "international-access",
        section: "Countries and transfers",
        label: "International access",
        value: "US support access to customer content is not confirmed or excluded.",
        lifecycleStage: "transfer",
        material: true,
        status: "missing",
        evidenceIds: ["ev-subprocessor-list"],
        dependentDimensionIds: ["vendor-transfer"],
      },
      {
        id: "security-controls",
        section: "Systems and vendors",
        label: "Technical controls",
        value:
          "Encryption, SSO, MFA, role-based access, logging, penetration testing, and incident response are evidenced or launch conditions.",
        lifecycleStage: "access",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-security-questionnaire", "ev-response-security"],
        dependentDimensionIds: ["security-controls"],
      },
      {
        id: "access-controls",
        section: "Staff and third-party access",
        label: "Staff access",
        value:
          "Personal tutors and authorised Student Services staff receive risk bands; named role membership remains to be approved.",
        lifecycleStage: "access",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-response-student-services", "ev-response-security"],
        dependentDimensionIds: ["security-controls"],
      },
      {
        id: "student-notice",
        section: "Transparency and rights",
        label: "Student notice and rights",
        value:
          "Existing notice omits individual scoring, combined support indicators, expected consequences, objection, and contest routes.",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-privacy-notice"],
        dependentDimensionIds: ["transparency-retention"],
      },
      {
        id: "retention",
        section: "Retention and deletion",
        label: "Retention period",
        value:
          "University schedule says academic year plus 90 days; vendor DPA says 24 months and negotiations propose 15 months.",
        lifecycleStage: "retention",
        material: true,
        status: "confirmed",
        evidenceIds: ["ev-retention-schedule", "ev-vendor-dpa", "ev-response-procurement"],
        dependentDimensionIds: ["transparency-retention"],
      },
      {
        id: "deletion-confirmation",
        section: "Retention and deletion",
        label: "Deletion confirmation",
        value: "The supplier has not supplied a deletion test or confirmation mechanism.",
        lifecycleStage: "deletion",
        material: true,
        status: "missing",
        evidenceIds: ["ev-vendor-dpa"],
        dependentDimensionIds: ["transparency-retention"],
      },
    ],
  },
  lifecycle: [
    {
      stage: "collection",
      data: ["Attendance", "VLE activity", "Attainment", "Library use", "Support indicators"],
      purpose: "Create a daily feature set for disengagement analysis",
      actors: ["Registry", "Digital Learning", "Student Services"],
      systems: ["Student record", "VLE", "Library", "Support systems"],
      location: "University systems, United Kingdom",
      recipients: ["University integration service"],
      legalBasis: "Public task proposed; final legal gateway to be confirmed",
      article9Condition: "Substantial public interest proposed; Schedule 1 condition unresolved",
      retention: "Source-system schedules apply",
      controls: ["Scheduled extraction", "Field allow-list"],
      missingFacts: ["Necessity of disability and wellbeing indicators"],
    },
    {
      stage: "storage",
      data: ["Feature rows", "Risk scores", "Intervention history"],
      purpose: "Hold inputs and outputs for scoring and case review",
      actors: ["Northstar Student Analytics Ltd"],
      systems: ["Vendor application and model store"],
      location: "Not evidenced",
      recipients: ["Vendor operations"],
      legalBasis: "Processor activity under university instructions",
      article9Condition: "Inherits unresolved university condition",
      retention: "Contract says 24 months; university says academic year plus 90 days",
      controls: ["Encryption at rest", "Tenant roles"],
      missingFacts: ["Hosting region", "Database region", "Backup location"],
    },
    {
      stage: "access",
      data: ["Individual risk band", "Contributing themes", "Support outcome"],
      purpose: "Enable authorised staff to review and plan outreach",
      actors: ["Personal tutors", "Student Services", "Vendor support"],
      systems: ["Vendor portal"],
      location: "University and unconfirmed vendor support locations",
      recipients: ["Named university roles"],
      legalBasis: "Public task proposed",
      retention: "Access logs retained under security schedule",
      controls: ["SSO", "MFA", "Role-based access", "Export logging"],
      missingFacts: ["Approved named roles", "Whether US support can access content"],
    },
    {
      stage: "use",
      data: ["Risk band", "Contributing themes", "Student context"],
      purpose: "Prioritise support outreach and inform authorised review",
      actors: ["Personal tutors", "Student Services"],
      systems: ["Vendor portal", "Student support case system"],
      location: "United Kingdom",
      recipients: ["Student support teams"],
      legalBasis: "Public task proposed; necessity and proportionality require officer judgement",
      article9Condition: "Required if disability or wellbeing indicator influences the score",
      retention: "Outcome enters the support case record under its own schedule",
      controls: ["Human review", "Context displayed", "Independent judgement expected"],
      missingFacts: ["Binding limits on escalation use", "Representative bias and accuracy tests"],
    },
    {
      stage: "sharing",
      data: ["Feature rows", "Risk scores", "Support outcomes"],
      purpose: "Provide the contracted analytics service",
      actors: ["University", "Vendor", "Subprocessors"],
      systems: ["Integration API", "Vendor platform"],
      location: "Subprocessor locations not mapped",
      recipients: ["Hosting", "Support", "Telemetry suppliers"],
      legalBasis: "Article 28 processor terms subject to evidence review",
      retention: "Varies by supplier; not mapped",
      controls: ["DPA", "Subprocessor notification"],
      missingFacts: ["Dataset-by-subprocessor map", "Service-order safeguards"],
    },
    {
      stage: "transfer",
      data: ["Potential customer content and telemetry"],
      purpose: "Remote support and infrastructure operation",
      actors: ["Vendor and subprocessors"],
      systems: ["Support and cloud systems"],
      location: "Possible United States access; unconfirmed",
      recipients: ["Vendor support", "Infrastructure providers"],
      legalBasis: "Chapter V mechanism not evidenced",
      retention: "Not evidenced",
      controls: ["Contractual transfer clause referenced but not supplied"],
      missingFacts: ["Transfer mechanism", "Transfer risk assessment", "Support-access locations"],
    },
    {
      stage: "retention",
      data: ["Inputs", "Scores", "Intervention records", "Logs"],
      purpose: "Operate, audit, and evaluate the service",
      actors: ["University records owner", "Vendor"],
      systems: ["Vendor platform", "University case system"],
      location: "University and vendor stores",
      recipients: ["Records Management", "Service owner"],
      legalBasis: "Storage limitation requires a documented necessity rationale",
      retention: "Unresolved: academic year plus 90 days versus 24 months",
      controls: ["University retention schedule", "Contract negotiation"],
      missingFacts: ["Agreed period", "Backup expiry", "Derived-feature treatment"],
    },
    {
      stage: "deletion",
      data: ["Student features", "Scores", "Backups", "Derived datasets"],
      purpose: "End processing when no longer necessary or at contract exit",
      actors: ["Vendor", "University service owner"],
      systems: ["Primary store", "Backups", "Analytics environment"],
      location: "All processing locations",
      recipients: ["University contract owner"],
      legalBasis: "Storage limitation and Article 28 return/deletion obligation",
      retention: "Deletion trigger not contractually reconciled",
      controls: ["Deletion or return clause"],
      missingFacts: ["Deletion verification", "Backup deletion lag", "Subprocessor confirmation"],
    },
  ],
  evidence,
  contradictions: [
    {
      id: "con-significant-effect",
      title: "Support-only description conflicts with escalation use",
      summary:
        "The intake says the score has no significant effect, while the operating procedure and Student Services response allow repeated scores into attendance escalation or fitness-to-study workflows.",
      dimensionIds: ["student-harms-rights"],
      sourceReferences: [
        { evidenceId: "ev-intake", excerpt: "support only ... does not itself make a decision" },
        {
          evidenceId: "ev-operating-procedure",
          excerpt: "may be considered in attendance escalation ... fitness-to-study referral",
        },
        {
          evidenceId: "ev-response-student-services",
          excerpt: "repeated alerts may be included in an attendance or fitness-to-study case file",
        },
      ],
      material: true,
      resolved: false,
    },
    {
      id: "con-retention",
      title: "Retention periods do not align",
      summary:
        "The university schedule requires deletion after the academic year plus 90 days, the vendor DPA permits 24 months, and current negotiations propose 15 months.",
      dimensionIds: ["transparency-retention"],
      sourceReferences: [
        {
          evidenceId: "ev-retention-schedule",
          excerpt: "current academic year plus 90 days",
        },
        { evidenceId: "ev-vendor-dpa", excerpt: "retained for 24 months" },
        { evidenceId: "ev-response-procurement", excerpt: "negotiate a 15-month deletion period" },
      ],
      material: true,
      resolved: false,
    },
  ],
  questions: [
    {
      id: "q-hosting",
      stakeholder: "Procurement/vendor management",
      text: "Where are the model, primary database, backups, and support systems hosted, and which entity operates each location?",
      blockedDimensionIds: ["vendor-transfer"],
      status: "unanswered",
    },
    {
      id: "q-subprocessors",
      stakeholder: "Procurement/vendor management",
      text: "Which subprocessors receive case data or customer content, for what purpose, and from which countries can they access it?",
      blockedDimensionIds: ["vendor-transfer"],
      status: "approved",
    },
    {
      id: "q-special-category",
      stakeholder: "Disability Services",
      text: "What student-support outcome requires disability or wellbeing flags, and could a less revealing feature achieve it?",
      blockedDimensionIds: ["legal-basis", "necessity-proportionality", "student-harms-rights"],
      status: "answered",
      response:
        "A registration flag could prevent missed support, but necessity is not established and inference risk remains. Test a model without the flag first.",
      answeredBy: "Amelia Lewis, Disability Services Manager",
      answeredAt: "2026-08-07T12:25:00Z",
    },
    {
      id: "q-access",
      stakeholder: "IT Security",
      text: "Which named university and supplier roles can view an individual score, contributing theme, export, or support record?",
      blockedDimensionIds: ["security-controls", "student-harms-rights"],
      status: "answered",
      response:
        "Personal tutors and authorised Student Services roles are proposed. Named membership, supplier support access, and bulk-export permissions remain to be approved.",
      answeredBy: "Priya Shah, Security Architect",
      answeredAt: "2026-08-07T09:40:00Z",
    },
    {
      id: "q-escalation",
      stakeholder: "Student Services",
      text: "Can a score influence attendance escalation, conduct, or fitness-to-study action, and what independent decision must occur first?",
      blockedDimensionIds: ["purpose-scope", "student-harms-rights"],
      status: "answered",
      response:
        "A high score starts support outreach. Repeated alerts may enter a case file, but authorised staff should review context and make an independent decision.",
      answeredBy: "Maya Bennett, Head of Student Support",
      answeredAt: "2026-08-06T10:15:00Z",
    },
    {
      id: "q-bias",
      stakeholder: "Academic schools",
      text: "What accuracy, false-positive, false-negative, subgroup, and intersectional results exist for a population comparable to this university?",
      blockedDimensionIds: ["student-harms-rights"],
      status: "answered",
      response:
        "Only aggregate precision and recall have been supplied. No representative university, subgroup, or intersectional evidence is available.",
      answeredBy: "Dr Samir Patel, Faculty Education Lead",
      answeredAt: "2026-08-08T08:50:00Z",
    },
    {
      id: "q-notice",
      stakeholder: "Registry",
      text: "How will students learn about the data sources, score logic and limits, likely consequences, human review, objection, and contest routes?",
      blockedDimensionIds: ["student-harms-rights", "transparency-retention"],
      status: "approved",
    },
    {
      id: "q-retention",
      stakeholder: "Procurement/vendor management",
      text: "Which retention period applies to inputs, scores, support outcomes, logs, backups, and subprocessors, and how will deletion be confirmed?",
      blockedDimensionIds: ["transparency-retention", "vendor-transfer"],
      status: "answered",
      response:
        "The university schedule and 24-month contract conflict. A 15-month period is proposed, but no deletion-confirmation mechanism has been agreed.",
      answeredBy: "Chloe Martin, Supplier Manager",
      answeredAt: "2026-08-08T14:20:00Z",
    },
  ],
  determinations: [
    {
      id: "det-purpose",
      dimensionId: "purpose-scope",
      question: "Is the purpose, scope, and affected population sufficiently defined?",
      outcome: "met",
      status: "confirmed",
      reasoning:
        "The support objective, student population, source systems, and proposed intervention are described. The downstream effect remains a separate material judgement.",
      evidenceReferences: [
        { evidenceId: "ev-intake", excerpt: "predicts disengagement and recommends outreach" },
        {
          evidenceId: "ev-data-dictionary",
          excerpt: "attendance ... disability/wellbeing support flags",
        },
      ],
      policyReferences: [{ ruleId: "uk-gdpr-art5", label: "UK GDPR Article 5 purpose limitation" }],
      dependencyFactIds: ["purpose", "intended-outcome", "data-subjects"],
      processingModelVersion: 3,
      reviewer: "Process Investigator",
      gaps: [],
    },
    {
      id: "det-lifecycle",
      dimensionId: "lifecycle-flows",
      question: "Is the data lifecycle mapped well enough to identify actors and controls?",
      outcome: "met",
      status: "confirmed",
      reasoning:
        "Eight lifecycle stages are mapped from collection through deletion. Unknown vendor locations remain isolated to the vendor/transfer determination.",
      evidenceReferences: [
        { evidenceId: "ev-data-dictionary", excerpt: "Daily features include" },
        { evidenceId: "ev-vendor-dpa", excerpt: "Customer data and derived risk scores" },
      ],
      policyReferences: [
        { ruleId: "ico-high-risk-criteria", label: "ICO DPIA processing description" },
      ],
      dependencyFactIds: ["data-sources", "processing-lifecycle", "system-landscape"],
      processingModelVersion: 3,
      reviewer: "Process Investigator",
      gaps: [],
    },
    {
      id: "det-legal-basis",
      dimensionId: "legal-basis",
      question: "Can the Article 6 and Article 9 basis be assessed?",
      outcome: "unclear",
      status: "needs-judgement",
      reasoning:
        "The proposed public-task and substantial-public-interest routes are explicit enough for officer assessment, but the legal gateway, Schedule 1 condition, and safeguards require confirmation.",
      evidenceReferences: [
        { evidenceId: "ev-response-registry", excerpt: "public task ... DPO confirmation" },
        {
          evidenceId: "ev-response-disability",
          excerpt: "could expose status through inference",
        },
      ],
      policyReferences: [
        { ruleId: "uk-gdpr-art6", label: "UK GDPR Article 6" },
        { ruleId: "uk-gdpr-art9", label: "UK GDPR Article 9 and DPA 2018 Schedule 1" },
      ],
      dependencyFactIds: ["legal-basis", "article-9-condition", "special-category-use"],
      processingModelVersion: 3,
      reviewer: "Privacy Assessor",
      gaps: ["Officer confirmation of legal gateway and Schedule 1 condition"],
    },
    {
      id: "det-necessity",
      dimensionId: "necessity-proportionality",
      question: "Are necessity and less intrusive means assessable?",
      outcome: "unclear",
      status: "needs-judgement",
      reasoning:
        "The stated service need and alternatives are documented. Whether special-category indicators and individual behavioural monitoring are proportionate remains a professional judgement requiring comparative testing.",
      evidenceReferences: [
        { evidenceId: "ev-intake", excerpt: "predicts disengagement" },
        { evidenceId: "ev-response-disability", excerpt: "necessity is not established" },
      ],
      policyReferences: [
        { ruleId: "uk-gdpr-art35", label: "UK GDPR Article 35(7)(b)" },
        { ruleId: "uk-gdpr-art5", label: "UK GDPR Article 5 data minimisation" },
      ],
      dependencyFactIds: ["necessity", "less-intrusive-means"],
      processingModelVersion: 3,
      reviewer: "Privacy Assessor",
      gaps: ["Reduced-feature comparison"],
    },
    {
      id: "det-harms",
      dimensionId: "student-harms-rights",
      question: "Are material effects, fairness harms, and student rights understood?",
      outcome: "unclear",
      status: "potential-issue",
      reasoning:
        "Consequential use is plausible, subgroup assurance is incomplete, and contest routes are absent. The assessor treats this as potentially high impact; the verifier requires the support/escalation boundary to be resolved.",
      evidenceReferences: [
        { evidenceId: "ev-operating-procedure", excerpt: "attendance escalation" },
        { evidenceId: "ev-model-card", excerpt: "Results by disability ... are not supplied" },
        { evidenceId: "ev-privacy-notice", excerpt: "does not describe individual scores" },
      ],
      policyReferences: [
        { ruleId: "uk-gdpr-art22", label: "UK GDPR Article 22 and profiling guidance" },
        { ruleId: "ico-high-risk-criteria", label: "ICO evaluation/scoring criteria" },
      ],
      dependencyFactIds: ["score-influence", "human-review", "bias-testing"],
      processingModelVersion: 3,
      reviewer: "Privacy Assessor",
      dissent:
        "The Independent Verifier agrees the evidence supports concern but says significance cannot be finalised until escalation governance is binding.",
      gaps: ["Representative bias testing", "Binding escalation boundary", "Contest process"],
    },
    {
      id: "det-vendor",
      dimensionId: "vendor-transfer",
      question: "Are processor, subprocessor, hosting, and transfer facts evidenced?",
      outcome: "unclear",
      status: "missing-evidence",
      reasoning:
        "The processor and basic contract are known, but hosting, remote access, subprocessor data flows, and any Chapter V mechanism are unsupported.",
      evidenceReferences: [
        { evidenceId: "ev-vendor-dpa", excerpt: "service order ... was not included" },
        { evidenceId: "ev-subprocessor-list", excerpt: "does not identify which receive" },
      ],
      policyReferences: [
        { ruleId: "uk-gdpr-art28", label: "UK GDPR Article 28" },
        { ruleId: "uk-gdpr-chapter-v", label: "UK GDPR Chapter V" },
      ],
      dependencyFactIds: ["vendor", "hosting", "subprocessors", "international-access"],
      processingModelVersion: 3,
      reviewer: "Privacy Assessor",
      gaps: ["Hosting region", "Subprocessor map", "Remote-access locations", "Transfer mechanism"],
    },
    {
      id: "det-security",
      dimensionId: "security-controls",
      question: "Are security controls evidenced sufficiently for screening?",
      outcome: "met",
      status: "confirmed",
      reasoning:
        "Core technical and organisational controls are evidenced or explicit launch conditions. Named role approval remains an implementation action rather than an unknown control category.",
      evidenceReferences: [
        {
          evidenceId: "ev-security-questionnaire",
          excerpt: "Encryption ... privileged actions are logged",
        },
        { evidenceId: "ev-response-security", excerpt: "SSO, MFA, role-based access" },
      ],
      policyReferences: [
        { ruleId: "uk-gdpr-art28", label: "UK GDPR Article 28 security assistance" },
      ],
      dependencyFactIds: ["security-controls", "access-controls"],
      processingModelVersion: 3,
      reviewer: "Independent Verifier",
      gaps: ["Approve named role membership before launch"],
    },
    {
      id: "det-transparency-retention",
      dimensionId: "transparency-retention",
      question: "Are transparency, consultation, retention, and deletion evidenced?",
      outcome: "not-met",
      status: "missing-evidence",
      reasoning:
        "The notice omits individual profiling and consequences, students have not been consulted, retention terms conflict, and deletion confirmation is unsupported.",
      evidenceReferences: [
        {
          evidenceId: "ev-privacy-notice",
          excerpt: "does not describe individual disengagement scores",
        },
        { evidenceId: "ev-retention-schedule", excerpt: "academic year plus 90 days" },
        { evidenceId: "ev-vendor-dpa", excerpt: "retained for 24 months" },
      ],
      policyReferences: [
        { ruleId: "uk-gdpr-arts13-14", label: "UK GDPR Articles 13 and 14" },
        { ruleId: "uk-gdpr-art5", label: "UK GDPR Article 5 storage limitation" },
      ],
      dependencyFactIds: ["student-notice", "retention", "deletion-confirmation"],
      processingModelVersion: 3,
      reviewer: "Privacy Assessor",
      gaps: ["Student consultation", "Agreed retention", "Deletion verification"],
    },
  ],
  risks,
  verification: {
    verdict: "verified-with-caveats",
    reviewedAt: "2026-08-12T15:45:00Z",
    reviewer: "Independent Verifier",
    blindedUntil: "2026-08-12T15:20:00Z",
    citationCoverage:
      "8/8 determinations cite evidence and policy; unsupported facts are explicit gaps.",
    unsupportedClaimIds: [],
    notes: [
      "The trigger recommendation is supported as a professional screening recommendation, not a legal determination.",
      "The assessor's view of material effect remains contingent on resolving the support/escalation boundary.",
      "No source supports a specific hosting region or transfer mechanism.",
    ],
  },
  audit: [
    {
      id: "audit-1",
      actor: "Alex Morgan",
      role: "Privacy Officer",
      action: "Created assessment",
      object: "Student Success Alert",
      timestamp: "2026-07-28T09:00:00Z",
      newValue: "Processing model v1",
    },
    {
      id: "audit-2",
      actor: "Process Investigator",
      role: "Professional-role agent",
      action: "Mapped lifecycle and evidence gaps",
      object: "Processing model",
      timestamp: "2026-08-03T10:10:00Z",
      newValue: "Processing model v2",
    },
    {
      id: "audit-3",
      actor: "Maya Bennett",
      role: "Head of Student Support",
      action: "Answered targeted question",
      object: "Score influence and escalation",
      timestamp: "2026-08-06T10:15:00Z",
    },
    {
      id: "audit-4",
      actor: "Priya Shah",
      role: "Security Architect",
      action: "Answered targeted question",
      object: "Staff access and controls",
      timestamp: "2026-08-07T09:40:00Z",
    },
    {
      id: "audit-5",
      actor: "Amelia Lewis",
      role: "Disability Services Manager",
      action: "Answered targeted question",
      object: "Special-category indicators",
      timestamp: "2026-08-07T12:25:00Z",
    },
    {
      id: "audit-6",
      actor: "Privacy Assessor",
      role: "Professional-role agent",
      action: "Applied UK policy pack",
      object: "Screening findings and risk register",
      timestamp: "2026-08-12T14:30:00Z",
      newValue: "Full DPIA likely — officer verification required",
    },
    {
      id: "audit-7",
      actor: "Independent Verifier",
      role: "Professional-role agent",
      action: "Completed blind evidence review",
      object: "Assessment findings",
      timestamp: "2026-08-12T15:20:00Z",
      newValue: "Verified with caveats",
    },
    {
      id: "audit-8",
      actor: "Independent Verifier",
      role: "Professional-role agent",
      action: "Reviewed recommendation after unblinding",
      object: "Screening recommendation",
      timestamp: "2026-08-12T15:45:00Z",
      newValue: "Citations complete; material-effect caveat preserved",
    },
    {
      id: "audit-9",
      actor: "Deterministic synthesizer",
      role: "System",
      action: "Validated structured artifacts",
      object: "Validated demo snapshot",
      timestamp: "2026-08-12T16:30:00Z",
      newValue: "Schema-valid, processing model v3, policy pack uk-dpia-2026.08-demo.1",
    },
  ],
  agentActivity: [
    {
      id: "activity-investigator",
      role: "Process Investigator",
      task: "Establish facts, map the lifecycle, surface contradictions, and draft questions",
      status: "completed",
      startedAt: "2026-08-12T13:30:00Z",
      completedAt: "2026-08-12T14:05:00Z",
      detail:
        "23 processing facts, 8 lifecycle stages, 2 material contradictions, and 8 targeted questions validated.",
    },
    {
      id: "activity-assessor",
      role: "Privacy Assessor",
      task: "Apply the UK policy pack and assess triggers, proportionality, harms, and residual risk",
      status: "completed",
      startedAt: "2026-08-12T14:06:00Z",
      completedAt: "2026-08-12T14:50:00Z",
      detail:
        "Eight determinations and eight student-impact risks produced against processing model v3.",
    },
    {
      id: "activity-verifier",
      role: "Independent Verifier",
      task: "Blindly review evidence, citations, contradictions, and rule application before recommendation access",
      status: "completed",
      startedAt: "2026-08-12T14:51:00Z",
      completedAt: "2026-08-12T15:45:00Z",
      detail:
        "Initial evidence review completed at 15:20; recommendation unblinded afterward and verified with caveats.",
    },
  ],
  policyPack: ukPolicyPack,
};

export const studentSuccessAlertSeed = dpiaCaseSnapshotSchema.parse(seed);

export function createStudentSuccessAlertSeed(): DpiaCaseSnapshot {
  return structuredClone(studentSuccessAlertSeed);
}
