"""Codex hook entrypoint for deterministic subagent routing.

Registered in the per-session private ``CODEX_HOME`` ``hooks.json``
generated by :mod:`omnigent.inner.codex_executor`. One subcommand:

- ``route-subagent`` (``PreToolUse``, matcher ``.*spawn_agent``) — asks
  the runner's ``route-subagent`` endpoint what model the spawn may use
  and rewrites / denies accordingly.

Stdlib-only and short-lived: ``PreToolUse`` blocks the spawn.

Codex encrypts the spawn ``message`` field in hook payloads, so routing
signal comes from ``task_name`` plus session metadata only, and the
original ``tool_input`` is echoed back verbatim on a rewrite.
"""

from __future__ import annotations

import sys
from typing import Any

from omnigent.inner.hook_scripts.subagent_router import (
    run_route_subagent_main,
)

# Codex flattens MCP-ish tool names, so the spawn tool arrives as
# ``collaborationspawn_agent`` on 0.145.x. Both the hooks.json matcher
# and this check must stay suffix-based rather than a bare literal.
SPAWN_AGENT_TOOL_SUFFIX = "spawn_agent"
# Harness label sent to the endpoint when argv names none.
DEFAULT_HARNESS = "codex"

_LABEL = "omnigent codex router hook"
_MODULE = "omnigent.inner.hook_scripts.codex_router_hook"


def main(argv: list[str] | None = None) -> int:
    """
    Dispatch a codex router-hook subcommand.

    :param argv: Argv override excluding the program name. ``None`` reads
        :data:`sys.argv`.
    :returns: Process exit code. Always ``0`` — verdicts travel on stdout
        so a hook failure never wedges codex.
    """
    raw_argv = sys.argv[1:] if argv is None else argv
    command = raw_argv[0] if raw_argv else ""
    if command == "route-subagent":
        return run_route_subagent_main(
            raw_argv[1:],
            prog=_prog(command),
            harness=DEFAULT_HARNESS,
            label=_LABEL,
            **ROUTE_SEAMS,
        )
    print(f"{_LABEL}: unknown subcommand {command!r}", file=sys.stderr)
    return 0


def _prog(command: str) -> str:
    return f"python -m {_MODULE} {command}"


def is_spawn_agent_tool(tool_name: Any) -> bool:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Report whether a hook payload names codex's subagent-spawn tool.

    :param tool_name: ``tool_name`` from the hook payload, e.g.
        ``"collaborationspawn_agent"``.
    :returns: ``True`` when the (flattened) name ends in
        ``spawn_agent``.
    """
    if not isinstance(tool_name, str):
        return False
    return tool_name.strip().lower().endswith(SPAWN_AGENT_TOOL_SUFFIX)


def with_system_message(
    output: dict[str, Any] | None,  # type: ignore[explicit-any]  # hook output JSON
) -> dict[str, Any] | None:  # type: ignore[explicit-any]  # hook output JSON
    """
    Add the routed-model notice codex's TUI surfaces to the user.

    A rewrite is otherwise invisible: codex reports no model change of its
    own, so the top-level ``systemMessage`` (alongside, not inside,
    ``hookSpecificOutput``) is the only place the decision shows up.

    :param output: Hook output from ``decision_to_hook_output``, or
        ``None`` for "no opinion".
    :returns: *output* with a ``systemMessage`` when it rewrote the spawn's
        model, otherwise *output* unchanged.
    """
    if not isinstance(output, dict):
        return output
    hook_output = output.get("hookSpecificOutput")
    if not isinstance(hook_output, dict) or hook_output.get("permissionDecision") != "allow":
        return output
    updated_input = hook_output.get("updatedInput")
    if not isinstance(updated_input, dict):
        return output
    model = updated_input.get("model")
    if not isinstance(model, str) or not model:
        return output
    return {**output, "systemMessage": f"Using Smart Routing. Routing to {model}."}


def _payload_model(payload: dict[str, Any]) -> str | None:  # type: ignore[explicit-any]  # hook payloads are untrusted JSON
    """
    Extract the parent session's model from a hook payload.

    :param payload: Codex hook payload.
    :returns: Model id, or ``None`` when the payload carries none.
    """
    model = payload.get("model")
    return model if isinstance(model, str) and model else None


#: How codex differs from the claude-native default: its own spawn-tool
#: name, its task-name keys, no prompt (codex encrypts the spawn message),
#: catalog ids injected verbatim, and the TUI routing notice.
ROUTE_SEAMS: dict[str, Any] = {  # type: ignore[explicit-any]  # route_pre_tool_use seams
    "tool_matcher": is_spawn_agent_tool,
    "task_keys": ("task_name", "agent_name"),
    "include_prompt": False,
    "parent_model_resolver": _payload_model,
    "model_translator_factory": None,
    "post_process": with_system_message,
}


if __name__ == "__main__":
    raise SystemExit(main())
